# ?? Datasource ???????????????????????????????????????????????
# En local : jdbc:mysql://localhost:3306/suiviprojet
# En Docker : la variable d'environnement SPRING_DATASOURCE_URL écrase cette valeur
spring.datasource.url=jdbc:mysql://localhost:3306/suiviprojet
spring.datasource.username=root
spring.datasource.password=

# ?? JPA ??????????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# ?? Serveur ??????????????????????????????????????????????????
server.port=8081