spring.datasource.url=jdbc:mysql://localhost:3306/suiviprojet
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

jwt.secret=secretkeysecretkeysecretkeysecretkey
jwt.expiration=86400000

# ── Configuration Gmail SMTP ──────────────────────────────
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saadiae474@gmail.com
spring.mail.password=gvhv pjau mpjp vgdh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com