services:

  # ── Base de données MySQL ──────────────────────────────────
  mysql:
    image: mysql:8.0
    container_name: suiviprojet-mysql
    restart: always
    environment:
      MYSQL_DATABASE: suiviprojet
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: suiviuser
      MYSQL_PASSWORD: suivipass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ── Backend Spring Boot ────────────────────────────────────
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: suiviprojet-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/suiviprojet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8085:8081"
    volumes:
      - ./docs:/docs




  # ── Frontend React ─────────────────────────────────────────
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: suiviprojet-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data: